# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: chatapp-back
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: chatapp-back
#   template:
#     metadata:
#       labels:
#         app: chatapp-back
#     spec:
#       nodeSelector:
#         "beta.kubernetes.io/os": linux
#       containers:
#       - name: chatapp-back
#         image: satvikregistry1.azurecr.io/azzimage0:latest
#         env:
#         - name: ALLOW_EMPTY_PASSWORD
#           value: "yes"
#         ports:
#         - containerPort: 6379
#           name: redis
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: chatapp-back
# spec:
#   ports:
#   - port: 6379
#   selector:
#     app: chatapp-back
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-front
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chatapp-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: chatapp-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: chatapp-front
        image: satvikregistry1.azurecr.io/azzimage0:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "chatapp-back"
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: chatapp-front
