apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: default
  labels:
    app: eks-sample-linux-app
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 80