apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: eks-sample-app
  labels:
    app: eks-sample-linux-app
spec:
  type: NodePort
  selector:
    app: eks-sample-linux-app
  ports:
    - nodePort: 31479
      port: 80
      targetPort: 80